[package]
name = "avrepro"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["serialize"], default-features = true }
serde = "1"
# avian3d = "=0.1.0"
avian3d = "=0.1.1"
